name: sample
services:
- name: sample
  image:
    registry_type: GHCR
    registry: "michelprogram"
    repository: "oui-lliam-app"
    registry_credentials: ${GHCR_CREDENTIALS}
    digest: ${SAMPLE_DIGEST}